[package]
name    = "influxdb"
version = "0.1.1"
authors = ["Leonhard Weber <leonhard.weber@voipir.cl>"]
edition = "2018"

[dependencies]
log          = {version = "*"}
serde        = {version = "*", features = ["derive"]}
serde_json   = {version = "*"}
chrono       = {version = "*", features = ["serde"]}
reqwest      = {version = "*", features = ["blocking", "json"]}

[dev-dependencies]
flexi_logger = {version = "*"}
